version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.3

jobs:
  lint-electron-secure-defaults:
    description: Run eslint Against Source Code
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: '18.16.0'
      - run:
          name: Installing Dependencies...
          command: npm install
      - run:
          name: Running Linter against Electron Secure Defaults...
          command: npm run lint

  build-electron-secure-defaults:
    description: Build and Package ESD 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.16.0'
      - run:
          name: Installing Dependencies...
          command: npm install
      - run:
          name: Compiling Typescript...
          command: npm run build
      - run:
          name: Packaging Application...
          command: mkdir .cache && npm run package
      - store_artifacts:
          path: package
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  electron-secure-defaults:
    jobs:
      - lint-electron-secure-defaults
      - build-electron-secure-defaults:
          requires:
            - lint-electron-secure-defaults
